### ISSUE TITLE
Nuget Package Ownership Request

### ISSUE THREAD

**Issue by conradreuter** [ibasin/Supermodel#1]
Hey Ilya!

I have a C# library idea and also came up with the name `Supermodel`. Since it seems like this project is not maintained anymore, would it be possible for you to transfer the ownership of the Nuget package to me?

Kind regards

**Comment by ibasin** [comment]
The project is maintained on BitBucket and at SupermodelFramework.com. If I
were to transfer the NuGet it would be confusing.

Sorry.

Ilya

**Comment by conradreuter** [comment]
Ah, sorry for the bothering then. It just seemed like the project is dead. I will come up with a new name then. :D

**Comment by ibasin** [comment]
No problem. Sorry again.
